name: Update Contributors

env:
  COMMIT_AUTHOR_NAME: hufilterbot
  COMMIT_AUTHOR_EMAIL: hufilter@protonmail.com
  COMMIT_MESSAGE: '[skip ci] Automatic update of contributors in package.json'

on:
  push:
    branches:
      - master

jobs:
  update-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json

      - name: Get contributors
        id: get-contributors
        uses: actions/github-script@v8
        with:
          script: |
            const { owner, repo } = context.repo;
            const contributors = await github.paginate(github.rest.repos.listContributors, { owner, repo });

            const sortedContributors = contributors.map((contributor) => ({
              name: contributor.login,
              url: `https://github.com/${contributor.login}`,
            }));

            // Set contributors as an output
            core.exportVariable('CONTRIBUTORS', JSON.stringify(sortedContributors));
            core.info(`Contributors: ${JSON.stringify(sortedContributors)}`);

      - name: Update contributors in package.json
        uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs/promises');
            const path = require('path');

            const bots = new Set(['dependabot[bot]', 'github-actions[bot]', 'hufilterbot']);

            const contributors = JSON.parse(process.env.CONTRIBUTORS).filter(({ name }) => !bots.has(name));

            const packageJsonPath = path.join(process.cwd(), 'package.json');
            const packageJson = JSON.parse(await fs.readFile(packageJsonPath, 'utf-8'));

            const existingContributors = new Set(packageJson.contributors || []);

            contributors.forEach(({ name, url }) => {
              existingContributors.add(`${name} (${url})`);
            });

            packageJson.contributors = Array.from(existingContributors).sort((a, b) => a.localeCompare(b));

            await fs.writeFile(packageJsonPath, JSON.stringify(packageJson, null, 2) + '\n');
            core.info('Updated contributors field in package.json');

      - name: Commit changes, if any
        id: git-commit
        run: |
          echo "Configuring git..."
          git config --local user.email "${{ env.COMMIT_AUTHOR_EMAIL }}"
          git config --local user.name "${{ env.COMMIT_AUTHOR_NAME }}"

          echo "Adding possible changes..."
          git add package.json

          echo "Checking for changes..."
          if git diff-index --cached --quiet HEAD; then
            echo "No changes to commit."
            echo "changes=false" >> $GITHUB_ENV
          else
            git commit -m "${{ env.COMMIT_MESSAGE }}"
            echo "changes=true" >> $GITHUB_ENV
          fi

      - name: Push changes, if any
        if: env.changes == 'true'
        run: |
          echo "Pushing changes..."
          git push
